//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitemaUnicesumar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnicesumarBdEntities : DbContext
    {
        public UnicesumarBdEntities()
            : base("name=UnicesumarBdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> ListBlock { get; set; }
        public virtual DbSet<Class> ListClass { get; set; }
        public virtual DbSet<Discipline> ListDiscipline { get; set; }
        public virtual DbSet<HeadOffice> ListHeadOffice { get; set; }
        public virtual DbSet<Laboratory> ListLaboratory { get; set; }
        public virtual DbSet<LaboratoryCapacity> ListLaboratoryCapacity { get; set; }
        public virtual DbSet<LaboratoryCategory> ListLaboratoryCategory { get; set; }
        public virtual DbSet<LaboratoryReserve> ListLaboratoryReserve { get; set; }
        public virtual DbSet<Shift> ListShift { get; set; }
        public virtual DbSet<User> ListUser { get; set; }
        public virtual DbSet<Horary> ListHorary { get; set; }
    }
}
