//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitemaUnicesumar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryReserve
    {
        public int Id { get; set; }
        public int LaboratoryId { get; set; }
        public int UserId { get; set; }
        public SitemaUnicesumar.Enum.ETypeReserve TypeReserveId { get; set; }
        public int ClassId { get; set; }
        public int ShiftId { get; set; }
        public int DisciplineId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int HoraryId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Laboratory Laboratory { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual User User { get; set; }
        public virtual Horary Horary { get; set; }
    }
}
