//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitemaUnicesumar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laboratory()
        {
            this.LaboratoryReserve = new HashSet<LaboratoryReserve>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int HeadOfficeId { get; set; }
        public int BlockId { get; set; }
        public int LaboratoryCategoryId { get; set; }
        public int LaboratoryCapacityId { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual HeadOffice HeadOffice { get; set; }
        public virtual LaboratoryCapacity LaboratoryCapacity { get; set; }
        public virtual LaboratoryCategory LaboratoryCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryReserve> LaboratoryReserve { get; set; }
    }
}
